<?php
namespace app\admin\controller;
use think\Controller;

class Category extends Controller
{
    private $obj;
    public function _initialize()
    {
        //parent::_initialize(); // TODO: Change the autogenerated stub
        $this->obj = model("Category");
    }

    public function index()
    {
        $parentID = input('get.parent_id',0,'intval');
        $categorys = $this->obj->getFirstCategorys($parentID);
        return $this->fetch('',[
            'categorys'=>$categorys,
        ]);
        //return '<style type="text/css">*{ padding: 0; margin: 0; } div{ padding: 4px 48px;} a{color:#2E5CD5;cursor: pointer;text-decoration: none} a:hover{text-decoration:underline; } body{ background: #fff; font-family: "Century Gothic","Microsoft yahei"; color: #333;font-size:18px;} h1{ font-size: 100px; font-weight: normal; margin-bottom: 12px; } p{ line-height: 1.6em; font-size: 42px }</style><div style="padding: 24px 48px;"> <h1>:)</h1><p> ThinkPHP V5<br/><span style="font-size:30px">十年磨一剑 - 为API开发设计的高性能框架</span></p><span style="font-size:22px;">[ V5.0 版本由 <a href="http://www.qiniu.com" target="qiniu">七牛云</a> 独家赞助发布 ]</span></div><script type="text/javascript" src="http://tajs.qq.com/stats?sId=9347272" charset="UTF-8"></script><script type="text/javascript" src="http://ad.topthink.com/Public/static/client.js"></script><thinkad id="ad_bd568ce7058a1091"></thinkad>';
    }

    public function add(){
        $categorys = $this->obj->getNormalFirstCategory();
        return $this->fetch('',[
            'categorys'=>$categorys,
        ]);
    }

    public function welcome(){
        return 'singwa';
    }

    public function save(){
//        print_r($_POST);
//        print_r(input('post.'));
//        print_r(request()->post());
//        做下严格判定
        if (!request()->isPost()){
            $this->error('请求失败');
        }
        $data = input('post.');
//        $data['status'] = 10;
        $validate = validate('Category');
        if (!$validate->check($data)){
            $this->error($validate->getError());
        }
        if (!$validate->scene('add')->check($data)){
            $this->error($validate->getError());
        }
        if (!empty($data['id'])){
            return $this->update($data);
        }
        //把$data 提交model层
        $res = $this->obj->add($data);
        if ($res){
            $this->success('新增成功');
        }else{
            $this->error('新增失败');
        }
    }

//    编辑页面
    public function edit($id=0){
        //echo input('get.id');
        //echo $id;
        if (intval($id)<1){
            $this->error('参数不合法');
        }

        $category = $this->obj->get($id);//print_r($category);exit();
        $categorys = $this->obj->getNormalFirstCategory();
        return $this->fetch('',[
            'categorys'=>$categorys,
            'category' =>$category,
        ]);
    }

    public function update($data){
        $res = $this->obj->save($data,['id'=>intval($data['id'])]);
        if ($res){
            $this->success('更新成功');
        }else{
            $this->error('更新失败');
        }
    }

    //排序逻辑
    public function listorder($id,$listorder){
        //echo $id."<br />";//测试
        //echo $listorder."<br />";
        $res = $this->obj->save(['listorder'=>$listorder],['id'=>$id]);
        if ($res){
            $this->result($_SERVER['HTTP_REFERER'],1,'success');
        }else{
            $this->result($_SERVER['HTTP_REFERER'],0,'更新失败');
        }
    }

    //修改状态
    public function status(){
        //print_r(input('get.'));测试
        $data = input('get.');
//        $data['status'] = 10;
        $validate = validate('Category');
        if (!$validate->scene('status')->check($data)){
            $this->error($validate->getError());
        }

        $res = $this->obj->save(['status'=>$data['status']],['id'=>$data['id']]);
        if ($res){
            $this->success('更新成功');
        }else{
            $this->error('更新失败');
        }
    }
}
